formatting changes; individual return values are returned from the init script.

diff --git a/junkbuster.init b/junkbuster.init
--- a/junkbuster.init
+++ b/junkbuster.init
@@ -36,6 +36,9 @@
 # 
 #  Revisions   :
 #     $Log$
+#     Revision 1.6  2001/06/28 13:38:42  sarantis
+#     formatting changes; individual return values are returned from the init script.
+#
 #     Revision 1.5  2001/06/11 11:37:40  sarantis
 #     Minor editing changes.
 #
@@ -96,25 +99,33 @@ stop () {
 }
 
 case "$1" in
-start)
+  start)
 	start	
 	;;
-stop)
+  stop)
 	stop	
 	;;
-restart)
+  reload|restart)
 	stop
 	start
+	RETVAL=$?
 	;;
-condrestart)
-	[ -f /var/lock/subsys/junkbuster ] && restart || : 
+  condrestart)
+	# restart only if already running
+	if [ -f /var/lock/subsys/junkbuster ] ; then
+		stop
+		start
+		RETVAL=$?
+		;;
+	fi 
 	;;
-status)
+  status)
 	status junkbuster
+	RETVAL=$?
 	;;
-*)
-	echo $"Usage: junkbuster {start|stop|restart|condrestart|status}"
+  *)
+	echo $"Usage: junkbuster {start|stop|reload|restart|condrestart|status}"
 	exit 1
 esac
 
-exit 0
+exit $RETVAL
